#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <sys/stat.h>
#include "covering_array.h"

covering_array_t *ca_create(int N, int k, int v, int t)
{
    covering_array_t *ca = malloc(sizeof(covering_array_t));
    if (ca == NULL) {
        return NULL;
    }

    ca->N = N;
    ca->k = k;
    ca->v = v;
    ca->t = t;
    ca->matrix = get_matrix(N, k);

    if (ca->matrix == NULL) {
        free(ca);
        return NULL;
    }

    return ca;
}

void ca_destroy(covering_array_t *ca)
{
    if (ca == NULL) {
        return;
    }

    if (ca->matrix != NULL) {
        free_matrix(ca->matrix, ca->N);
    }

    free(ca);
}

int ca_validate(covering_array_t *ca)
{
    if (ca == NULL || ca->matrix == NULL) {
        return 0;
    }

    size_t R = binomial(ca->k, ca->t);
    size_t C = 1;
    for (int i = 0; i < ca->t; i++) {
        C *= (size_t)ca->v;
    }

    int **IToC = get_matrix((int)R, ca->t);
    t_wise(IToC, ca->k, ca->t);

    int **P = get_matrix((int)R, (int)C);
    for (size_t i = 0; i < R; i++) {
        for (size_t j = 0; j < C; j++) {
            P[i][j] = 0;
        }
    }

    for (int i = 0; i < ca->N; i++) {
        for (size_t j = 0; j < R; j++) {
            int c = get_col(ca->matrix[i], IToC, (int)j, ca->t, ca->v);
            if (c != -1) {
                P[j][c]++;
            }
        }
    }

    size_t covered = 0;
    for (size_t i = 0; i < R; i++) {
        for (size_t j = 0; j < C; j++) {
            if (P[i][j] > 0) {
                covered++;
            }
        }
    }

    size_t total = R * C;
    int valid = (covered == total);

    free_matrix(IToC, (int)R);
    free_matrix(P, (int)R);

    return valid;
}

covering_array_t *ca_load(const char *filename)
{
    FILE *fp = fopen(filename, "r");
    if (fp == NULL) {
        fprintf(stderr, "Error: cannot open file '%s'\n", filename);
        return NULL;
    }

    char line[1024];
    long pointer = ftell(fp);
    while (fgets(line, sizeof(line), fp) != NULL) {
        if (line[0] != 'C' && line[0] != 'c') {
            break;
        }
        pointer = ftell(fp);
    }
    fseek(fp, pointer, SEEK_SET);

    int N, k, v, t;
    if (fscanf(fp, "%d %d %d ^ %d %d", &N, &k, &v, &k, &t) != 5) {
        fprintf(stderr, "Error: invalid file format\n");
        fclose(fp);
        return NULL;
    }

    covering_array_t *ca = ca_create(N, k, v, t);
    if (ca == NULL) {
        fclose(fp);
        return NULL;
    }

    for (int i = 0; i < N; i++) {
        for (int j = 0; j < k; j++) {
            if (fscanf(fp, "%d", &ca->matrix[i][j]) != 1) {
                fprintf(stderr, "Error: failed to read matrix element at (%d,%d)\n", i, j);
                ca_destroy(ca);
                fclose(fp);
                return NULL;
            }
        }
    }

    fclose(fp);
    return ca;
}

int ca_save(const char *folder_path, covering_array_t *ca, const char *comment, int missing)
{
    if (ca == NULL || ca->matrix == NULL) {
        return -1;
    }

    struct stat st;
    if (stat(folder_path, &st) != 0 || !S_ISDIR(st.st_mode)) {
        fprintf(stderr, "Error: folder '%s' does not exist\n", folder_path);
        return -1;
    }

    char filename[1024];
    if (missing > 0) {
        snprintf(filename, sizeof(filename), "%s/N%dk%dv%d^%dt%d.ca.missing%d",
                 folder_path, ca->N, ca->k, ca->v, ca->k, ca->t, missing);
    } else {
        snprintf(filename, sizeof(filename), "%s/N%dk%dv%d^%dt%d.ca",
                 folder_path, ca->N, ca->k, ca->v, ca->k, ca->t);
    }

    FILE *fp = fopen(filename, "w");
    if (fp == NULL) {
        fprintf(stderr, "Error: cannot create file '%s'\n", filename);
        return -1;
    }

    if (comment != NULL && comment[0] != '\0') {
        fprintf(fp, "C %s\n", comment);
    } else {
        fprintf(fp, "C Generated by covering-array library\n");
    }

    fprintf(fp, "%d %d %d ^ %d %d\n", ca->N, ca->k, ca->v, ca->k, ca->t);

    for (int i = 0; i < ca->N; i++) {
        for (int j = 0; j < ca->k; j++) {
            fprintf(fp, "%d ", ca->matrix[i][j]);
        }
        fprintf(fp, "\n");
    }

    fclose(fp);
    return 0;
}

void ca_print(covering_array_t *ca)
{
    printf("CA(%d; %d, %d, %d)\n", ca->N, ca->t, ca->k, ca->v);
    printf("Matrix:\n");
    for (int i = 0; i < ca->N; i++) {
        for (int j = 0; j < ca->k; j++) {
            printf("%d ", ca->matrix[i][j]);
        }
        printf("\n");
    }
}